### ISSUE TITLE
Question about compute_greedy_homotopy_basis

### ISSUE THREAD

**Issue by Frank-Dz** [group-gu/geometry-processing-package#3]
If it is possible to use compute greedy homotopy basis on a graph structure(which can be non-manifold) like Medial Surface？

**Comment by cfwen** [comment]
my code probably does not work on non-manifold and I don't know an algorithm that maybe work. you may use some tools to fix non-manifold problems.

**Comment by Frank-Dz** [comment]
> my code probably does not work on non-manifold and I don't know an algorithm that maybe work. you may use some tools to fix non-manifold problems.

ok！ Thank you！
